jauth-url: 
  http://127.0.0.1:8440/jauth
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.245.175:3306/cocdev?characterEncoding=utf8&useSSL=true
    username: cocdev
    password: cocdev