server:
  port: 8441
  context-path: /
spring:
  profiles:
    active: dev
  application:
    name: loc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.245.175:3306/cocdev?characterEncoding=utf8&useSSL=true
    username: cocdev
    password: cocdev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
security: 
  basic:
    enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "${jauth-url}/eureka/"
  instance:
    leaseExpirationDurationInSeconds: 1
    leaseRenewalIntervalInSeconds: 1
context:
  component-scan:
    base-package: com.asiainfo.biapp.si.loc.*
  bean:
    classes: com.asiainfo.biapp.si.loc.base.LocCacheBase
  listener:
    classes: com.asiainfo.biapp.si.loc.springlistener.LocBaseListener
  