server:
  port: @port-loc@
  context-path: @ctx-loc@
spring:
  profiles:
    active: @env@
  application:
    name: loc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  boot:
    admin:
      url: "${jauth-url}/sba/"
security: 
  basic:
    enabled: false
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "${jauth-url}/eureka/"
  #instance:
    #leaseExpirationDurationInSeconds: 1
    #leaseRenewalIntervalInSeconds: 1
autoLoginSign: xm8EV6Hy5RMFK4EEACIDAwQus
context:
  component-scan:
    base-package: com.asiainfo.biapp.si.loc.*
  bean:
    classes: com.asiainfo.biapp.si.loc.base.LocCacheBase
  listener:
    classes: com.asiainfo.biapp.si.loc.base.listener.LocBaseListener
info:
  app:  
    name: "LOC"  
    description: "标签运营中心-亚信"  
version: "5.0.0"  
