server:
  port: 8442
  context-path: /
spring:
  profiles:
    active: dev
  application:
    name: gateway
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: "${jauth-url}/eureka/"
  instance:
    leaseExpirationDurationInSeconds: 600000
    leaseRenewalIntervalInSeconds: 6000000
zuul:
  host:
    connect-timeout-millis: 60
    socket-timeout-millis: 60
  routes:
    loc:
      path: /**
      serviceId: loc
    jauth:
      path: /jauth/**
      serviceId: jauth
ribbon:
  readTimeout: 60000
  connectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false