jauth-url: 
  http://192.168.252.52/jauth
acrm-url:
  http://192.168.252.54/acrm
loadLevel:
  1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.248.142:3306/coc_suit?useUnicode=true&characterEncoding=utf-8
    username: cocsuit
    password: cocsuit
  boot:
    admin:  
      client:
        serviceUrl: http://192.168.248.166:18880/loc