jauth-url: 
  http://10.3.232.192/jauth
acrm-url:
  http://10.3.232.193/acrm
loadLevel:
  1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.3.232.106:3306/ywcoc?useUnicode=true&characterEncoding=utf-8
    username: ywcoc
    password: Ywcoc_123
  boot:
    admin:  
      client:
        serviceUrl: http://10.3.232.192:18880/loc